export const environment = {
  production: true,
  apiBaseUrl: 'https://6a02c43e0d92f63dd25406d7.mockapi.io/api/v1',
  usersEndpointPath: '/users',
  plansEndpointPath: '/plans',
  alertPreferencesEndpointPath: '/alert_preferences',
  supportTicketsEndpointPath: '/support_tickets',
  plotsEndpointPath: '/plots',
  cropsEndpointPath: '/crops',
  soilRecordsEndpointPath: '/soil_records',
  irrigationRecommendationsEndpointPath: '/irrigation_recommendations',
  irrigationSchedulesEndpointPath: '/irrigation_schedules',
  climateAlertsEndpointPath: '/climate_alerts',
  yieldSummariesEndpointPath: '/yield_summaries',
  lossSummariesEndpointPath: '/loss_summaries',
  waterConsumptionsEndpointPath: '/water_consumptions',
};
