export const DEPARTMENT_TO_CITY: Record<string, string> = {
  'Amazonas':     'Chachapoyas',
  'Áncash':       'Huaraz',
  'Apurímac':     'Abancay',
  'Arequipa':     'Arequipa',
  'Ayacucho':     'Ayacucho',
  'Cajamarca':    'Cajamarca',
  'Callao':       'Callao',
  'Cusco':        'Cusco',
  'Huancavelica': 'Huancavelica',
  'Huánuco':      'Huanuco',
  'Ica':          'Ica',
  'Junín':        'Huancayo',
  'La Libertad':  'Trujillo',
  'Lambayeque':   'Chiclayo',
  'Lima':         'Lima',
  'Loreto':       'Iquitos',
  'Madre de Dios':'Puerto Maldonado',
  'Moquegua':     'Moquegua',
  'Pasco':        'Cerro de Pasco',
  'Piura':        'Piura',
  'Puno':         'Puno',
  'San Martín':   'Moyobamba',
  'Tacna':        'Tacna',
  'Tumbes':       'Tumbes',
  'Ucayali':      'Pucallpa'
};
